<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pbvk</string>
		<string>pbmk</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Pixel Bender 3D</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|while|for|return)\b</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((min|max|default)Value|description|languageVersion)\b</string>
			<key>name</key>
			<string>meta.doctype.pixelbender3d</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;</string>
			<key>end</key>
			<string>&gt;</string>
			<key>name</key>
			<string>meta.pixelbender3d</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b((min|max|default)Value|description|languageVersion|namespace|vendor|version|id|index)\b</string>
					<key>name</key>
					<string>constant.doctype.pixelbender3d</string>
				</dict>
				<dict>
					<key>match</key>
					<string>".*"</string>
					<key>name</key>
					<string>string.quoted.double.pixelbender3d</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[0-9]+\.[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.float</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.int</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\.[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.float</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.int</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;[^&gt;]*&gt;</string>
			<key>name</key>
			<string>meta.doctype.pixelbender3d</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.pixelbender3d</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.pixelbender3d</string>
				</dict>
				<key>3</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.pixelbender3d</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.variable</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:([a-zA-Z\d]+)\s+([a-zA-Z\d]+),?\s*)</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\b[a-zA-Z\d]+)\s+([a-zA-Z\d]+(\(.*?\)))</string>
			<key>name</key>
			<string>entity.type.modifier.pixelbender3d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bool(2|3|4)?|pixel(1|2|3|4)|image(1|2|3|4)|float(2|3|4|2x2|3x3|4x4)?|int(2|3|4)?|region|void)\b</string>
			<key>name</key>
			<string>support.class.pixelbender3d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(kernel|parameter|(in|out)put|vertex|material|interpolated|import|dependent|const)\b</string>
			<key>name</key>
			<string>keyword.pixelbender3d</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.pixelbender3d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.pixelbender3d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(evaluateVertex|evaluateFragment|radians|degrees|sin|cos|tan|asin|acos|atan|pow|exp|exp2|log|log2|sqrt|inverseSqrt|abs|sign|floor|ceil|fract|mod|min|max|step|clamp|mix|smoothStep|length|distance|dot|cross|normalize|matrixCompMult|(greater|less)Than(Equal)?|equal|notEqual|any|all|not|sample|dod)\b</string>
			<key>name</key>
			<string>support.function.pixelbender3d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#\b(if|ifdef|endif|defined|elif|define)\b\n</string>
			<key>name</key>
			<string>entity.name.preprocessor</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^#.*\n</string>
			<key>name</key>
			<string>other.preprocessor</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pixelbender3d</string>
	<key>uuid</key>
	<string>0712573C-0BA5-42CC-BA7E-4ACDBD084AC4</string>
</dict>
</plist>
